### ISSUE TITLE
Python 3.7 is currently broken

### ISSUE THREAD

**Issue by seenbuklee** [aerosoul94/fatx-tools#3]
I was able to fix it by installing version 2.7.2
if i try to fix it it just keeps going on and on and on with finding new errors.

```
G:\>main_recover.py -i XBOX_IMAGE.img -o xna -n 2 -r -so
Traceback (most recent call last):
  File "G:\main_recover.py", line 6, in <module>
    from fatx_analyzer import FatXAnalyzer
  File "G:\fatx_analyzer.py", line 1, in <module>
    from fatx_filesystem import FatXDirent, VALID_FILE_ATTRIBUTES
  File "G:\fatx_filesystem.py", line 249
    print 'Failed to set timestamps.'
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Failed to set timestamps.')?
```

**Comment by aerosoul94** [comment]
Yeah I've always used Python 2.7 but it should be easy to add Python 3 support. It is in the TODO list within the README by the way.
